# Generated by Django 5.1.2 on 2024-10-19 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('vote_count', models.IntegerField(default=0)),
                ('commentator', models.CharField(max_length=255)),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('image_src', models.ImageField(upload_to='images/')),
                ('posted_by', models.CharField(max_length=255)),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Threads',
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='threef.thread'),
        ),
    ]
