# Generated by Django 5.1.2 on 2024-10-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0002_comment_thread_delete_threads_comment_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
