# Generated by Django 5.1.2 on 2024-10-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0003_comment_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_posted',
            new_name='time_ago',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='time_posted',
            new_name='time_ago',
        ),
    ]
