# Generated by Django 5.1.2 on 2024-10-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0004_rename_time_posted_comment_time_ago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='image_src',
            new_name='imageSrc',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='posted_by',
            new_name='postedBy',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='time_ago',
            new_name='timeAgo',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='vote_count',
            new_name='voteCount',
        ),
    ]
