# Generated by Django 5.1.2 on 2024-10-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0005_rename_image_src_thread_imagesrc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_ago',
            new_name='postedDateComment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='vote_count',
            new_name='voteCountComment',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='timeAgo',
            new_name='postedDate',
        ),
    ]
