# Generated by Django 5.1.2 on 2024-10-29 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('imageSrc', models.CharField(max_length=500)),
                ('postedBy', models.CharField(max_length=255)),
                ('postedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('voteCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('voteCountComment', models.IntegerField(default=0)),
                ('commentator', models.CharField(max_length=255)),
                ('postedDateComment', models.DateTimeField(default=django.utils.timezone.now)),
                ('selected', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='threef.thread')),
            ],
        ),
    ]
