# Generated by Django 5.1.2 on 2024-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='imageSrc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
