# Generated by Django 5.1.2 on 2024-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0002_alter_thread_imagesrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='imageSrc',
            field=models.CharField(max_length=500),
        ),
    ]
