# Generated by Django 5.1.2 on 2024-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0003_alter_thread_imagesrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='functionality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='marking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='shape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='smell',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='texture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
