# Generated by Django 5.1.2 on 2024-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0004_thread_color_thread_functionality_thread_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='functionality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='marking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
