# Generated by Django 5.1.2 on 2024-11-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0005_alter_thread_description_alter_thread_functionality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
