# Generated by Django 5.1.2 on 2024-11-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0006_alter_thread_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
