# Generated by Django 5.1.2 on 2024-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threef', '0007_thread_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
